apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  labels:
    app: wp-mysql
    component: wp-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi