apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: wp-mysql
    component: mysql-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-mysql
      component: mysql-sts-container
  serviceName: mysql
  template:
    metadata:
      labels:
        app: wp-mysql
        component: mysql-sts-container
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "supersecretpassw0rd"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi